coverage_service: coveralls
xcodeproj: MathExpression.xcodeproj
scheme: MathExpression-iOS
source_directory: MathExpression/*
ignore:
  - MathExpressionPerformanceTests/*
  - MathExpressionTestHelpers/*
  - MathExpressionTests/*