language: swift
osx_image: xcode10.3

cache: bundler

jobs:
  include:
  - stage: build
    name: "Building iOS"
    script: bundle exec fastlane build platform:'iOS'

  - stage: build
    name: "Building tvOS"
    script: bundle exec fastlane build platform:'tvOS'

  - stage: build
    name: "Building macOS"
    script: bundle exec fastlane build platform:'macOS'

  - stage: test
    name: "Running tests"
    script: bundle exec fastlane ios test device:'iPhone 8'
    after_success: bundle exec slather

  - stage: test
    name: "Running performance tests"
    script: bundle exec fastlane ios test_performance device:'iPhone 8'
    after_success: bundle exec slather

stages:
- name: build
  if: (type = pull_request OR type = push) AND branch = master

- name: test
  if: (type = pull_request OR type = push) AND branch = master

after_script: Scripts/telegram_notification.sh