language: swift
osx_image: xcode10.3

install:
  - bundle install --without=documentation

jobs:
  include:
  - stage: test
    name: "Running tests"
    script: bundle exec fastlane ios test device:'iPhone 8'

  - stage: test
    name: "Running performance tests"
    script: bundle exec fastlane ios test_performance device:'iPhone 8'

stages:
- name: test
  if: type = pull_request AND branch = master
